### ISSUE TITLE
[Safari] Please add link to this Github-Repo

### ISSUE THREAD

**Issue by clemensbartz** [duckduckgo/duckduckgo-privacy-extension#101]
### Information about your system

- Extension Version: 2018.1.25
- Browser and Version: Safari 11.0.3
- Operating System: MacOS 10.13.3 High Sierra

### What does not work?

When I click on "more options" (Hamburger Menu), I cannot find a link to this repository.

### What is the expected behavior?

Please add a link to this repository in the "more options" menu and/or in the settings menu.

**Comment by alohaas** [comment]
Hi @clemensbartz, thank you for sharing this feedback. We handle suggestions like this internally so I will be bringing your thoughtful request to the team.

Thanks again!

**Comment by brindy** [comment]
Hi folks,

Things have moved on a bit since this was last updated.

We have a new extension for Safari that uses Tracker Radar and you can install it from the App Store:
https://apps.apple.com/us/app/duckduckgo-privacy-essentials/id1482920575?mt=12

You can find the code for it here:
https://github.com/duckduckgo/privacy-essentials-safari

Thanks!
