### ISSUE TITLE
'Ask Dax' on context menu

### ISSUE THREAD

**Issue by aforty** [duckduckgo/duckduckgo-privacy-extension#104]
I'm using the DDG Privacy Essentials extension and it appears to add 'Ask Dax' into the right-click context menu on pages. 

1. Selecting 'Ask Dax' doesn't appear to do anything
2. I would like to see a setting somewhere to remove this context menu item

I'm using version 2018.1.9 on Safari 11.0.3 (13604.5.6).

![screen shot 2018-01-29 at 4 27 10 pm](https://user-images.githubusercontent.com/523683/35535366-4e0dd970-0511-11e8-86e2-5495893f6adb.png)

**Comment by dharb** [comment]
Hey @aforty, thank you for the feedback! Indeed, this context menu item was a bug that we have since removed (see https://github.com/duckduckgo/duckduckgo-privacy-extension/commit/d240c4bc8623676ec5998da9426fb4e46997e864#diff-c893298ad3d76f3ab4b31697d56aac47). It can sometimes take a few days for updates to be approved in the Safari Gallery, but I can assure you it'll disappear on your next update.
