### ISSUE TITLE
[Firefox Mobile] Not working?

### ISSUE THREAD

**Issue by Lionirdeadman** [duckduckgo/duckduckgo-privacy-extension#105]
If you click on the extension while on a page or anywhere, the extension thinks you're in a new tab which leads me to believe it's not working at all.

**Comment by BigNickBurgess** [comment]
Seconded this, is it working on mobile? If so then it needs to update correctly for mobile.

**Comment by alohaas** [comment]
Hey @Lionirdeadman and @BigNickBurgess, our browser extensions are only intended to be used on desktop. Instead, we have a mobile browser for iOS and Android that you can download should you wish to use the DuckDuckGo Privacy Essentials on your phone. You can find links to download both at the bottom of this page - https://duckduckgo.com/app.

**Comment by BigNickBurgess** [comment]
Thats a shame as I prefer to use Firefox and all its extensions on mobile as thats its biggest selling point,  I already have DDG privacy browser as a quick use thing (mainly for Oreo autofill support) but I use FF more.  Is it really that big a step to make it work properly on mobile FF? Since numerous other extensions support it.

**Comment by Lionirdeadman** [comment]
Same feeling here
