### ISSUE TITLE
Squarespace sites break with extension enabled in Firefox

### ISSUE THREAD

**Issue by autonome** [duckduckgo/duckduckgo-privacy-extension#119]
I've noticed a few sites breaking and realized that they're Squarespace sites and they only break when I have the DDG extension enabled.

Example: http://rickpinchera.com/animation/

The console shows a bunch of requests blocked due to CORS headers missing.

**Comment by laurengarcia** [comment]
Confirming this issue on Firefox (only). Seems that a couple of the <script> tags on the main_frame page are loaded like this (do a view-source on http://rickpinchera.com/animation/ to see) :

`<script crossorigin="anonymous" src="//static.squarespace.com/universal/scripts-compressed/common-8f311ad04829ea3a6d29-min.en-US.js" ></script>`

The `crossorigin` attribute is triggering CORS issue in Firefox (I think). Only workaround in Firefox is to add a security exception. Fix is: Site owner (or Squarespace) needs to remove the crossorigin attribute. I'm not sure we can do anything here because our https rules are upgrading the requests properly and the scripts are available over https. Perhaps if this issue is super-pervasive, we should stop trying to upgrade those requests on the extension side.

Details here:
https://stackoverflow.com/questions/41069330/with-script-crossorigin-anonymous-why-is-a-script-blocked-by-cors-policy/41069421#41069421

**Comment by laurengarcia** [comment]
Spent a few minutes looking at other sites on Squarespace and can confirm that this is happening on other sites created/hosted there as well, another example: http://www.bensellon.com/

**Comment by andrey-p** [comment]
Not doing HTTPS upgrades for `static.squarespace.com` and `static1.squarespace.com` seems to fix things.

**Comment by laurengarcia** [comment]
Update: we are removing the Squarespace urls from our upgrade list since alot of Squarespace sites seem to have a similar issue. Those changes should be published later today. Your extension should pick up changes automatically.

**Comment by laurengarcia** [comment]
Fix went live earlier today (sorry for lag). I'm seeing images again in Firefox with the DDG extension enabled on http://rickpinchera.com/animation/. The extension is configured to ping our server every half hour for changes to the https upgrade list, once you get that list you'll see the fix.

Here's what I'm seeing with a fresh install on Firefox:
![https-update](https://user-images.githubusercontent.com/1278969/36002415-f0504072-0cde-11e8-9041-b420d22e4414.png)

**Comment by laurengarcia** [comment]
The other Squarespace site we identified is also fixed: http://www.bensellon.com/
Thanks @autonome for bringing this to our attention, quite an unusual bug. Interesting and helpful for us.

![bensellon com](https://user-images.githubusercontent.com/1278969/36002503-42bec9c8-0cdf-11e8-8441-df2b00cc378c.png)

**Comment by autonome** [comment]
Yay, thanks @laurengarcia!
