### ISSUE TITLE
Don't show the search terms in the URL

### ISSUE THREAD

**Issue by as-muncher** [duckduckgo/duckduckgo-privacy-extension#1496]
When I use duckduckgo the search engine, my search terms end up in the URL, so basically my internet service provider can see what I'm searching for.  I guess if I want more anonymity, I should use TOR browser.  I know Yahoo used to do it where the search term doesn't show up in the URL.  Couldn't duckduckgo do something like this too?

**Comment by dharb** [comment]
We do! Go to the [privacy settings page](https://duckduckgo.com/settings#privacy) and toggle the GET Requests setting to off in order to remove search terms from the url.

FYI though: because your connection to https://duckduckgo.com is encrypted, your ISP can’t see your search terms anyway, so this setting isn’t necessary. Check out [this article](https://spreadprivacy.com/protection-from-isp-spying/) for a full explanation.

**Comment by as-muncher** [comment]
I had no idea you had a privacy settings page.  I just wouldn't want to be putting in search terms and thinking I'm safe and then find out later that I actually wasn't.  Thanks for the reply.  So I don't even have to enable the "URLs over HTTPS" thing in my browser?  or duckduckgo plugin does it anyways?  I posted this issue in the plugin repository, but mean it for anywhere.  When I visit the duckduckgo website without having the duckduckgo plugin installed, I still would be wondering if my ISP can see my search terms in the URL.

**Comment by dharb** [comment]
That’s right, anytime you’re searching on DuckDuckGo your connection is encrypted and your ISP cannot see your search terms: 
![](https://spreadprivacy.com/content/images/2019/05/Before-after-slash-difference.png)

**Comment by as-muncher** [comment]
Ok, thanks.  I'm probably not the only person who has wondered about that, though.  Maybe it's something to consider to put a plain text line at the top stating that your ISP can't see the search terms in your URL because duckduckgo is encrypted?  just a thought.
