### ISSUE TITLE
Known good websites are now being blocked

### ISSUE THREAD

**Issue by JCL324** [duckduckgo/duckduckgo-privacy-extension#1845]
## Description

The website I need for my health insurance stopped working about a week ago. I can get to the login screen, but on submit to get to my account, I get `The requested URL was rejected`. Works fine in Private mode or if I disable your plugin.

## Steps to Reproduce

1. Go to https://my.cigna.com/web/public/guest I realize most won't have an account :(

**Expected behavior:**

Should get to this page: https://my.cigna.com/web/public/guest/mfa

**Actual behavior:**

I get "The requested URL was rejected. Please contact...."

**Versions**

- Extension: 2023.3.15.1
- Browser: Firefox (up to date)
- OS: MacOS

**Comment by AlexCuan** [comment]
Doesn't seem blocked for me. Tried on Vivaldi and Firefox, both with DDG extension 2023.3.15.1

**Comment by dharb** [comment]
@JCL324 thank you for filing this issue - it can be difficult for us to detect when privacy protections cause issues on websites that require a difficult to create account to test, so we really appreciate the report. I shipped a config change that should resolve the issue, but I can't actually confirm it without an account. When you have a moment, could you please try again with our extension installed and let me know if the issue persists?

**Comment by JCL324** [comment]
It works!! Thank you so much! Mind pointing me to what you did fix? Curious as to how this all works.

**Comment by dharb** [comment]
Excellent! Thank you for confirming. The problem turned out to be that we were blocking a [script](https://p.login.my.cigna.com/public/digital-experience/js/common.js) on the page from loading because we caught it performing some pretty heavy canvas fingerprinting in our last crawl, which is an increasingly common technique trackers use to maintain a persistent, cookie-less identifier for users. Unfortunately, we've started seeing this same technique used by more and more websites as a form of fraud prevention, which seems to be the case here.

We generally don't interfere with first-party scripts, but in this particular case Cigna is using a CNAME to serve the script from a third-party domain (something websites like to do to make requests to third-party domains look like they're first-party), so we blocked it. To fix the issue, I allowed this request to load on cigna.com, which you can see [here](https://github.com/duckduckgo/privacy-configuration/pull/832) and [here](https://github.com/duckduckgo/privacy-configuration/pull/821/files).

If you're curious about how we caught this script fingerprinting in the first place, check out [Tracker Radar](https://github.com/duckduckgo/tracker-radar), which is where we share the results of our monthly crawls.

I hope this is helpful, and please don't hesitate to report any other breakage you encounter here so we can get it fixed for you.
