### ISSUE TITLE
Header bar missing when using DuckDuckGo Privacy Essentials

### ISSUE THREAD

**Issue by JonLoesch** [duckduckgo/duckduckgo-privacy-extension#1902]
## Description
On this website: https://www.harpygee.com/
There is a header `div` that contains navigation elements, social media links, etc... as well as an ad.
DuckDuckGo Privacy essentials applies `hidden`, `display: none`, to the whole div, and not just the ad (which I'm *assuming* is what's triggering it)

## Steps to Reproduce

1. Load the page with the extension loaded
2. Load the page without the extension loaded

**Expected behavior:**
The ads in the top bar and in the side bar are greyed out

**Actual behavior:**
The ad in the side bar is greyed out no problem, but the entire header nav disappears

**Versions**
- Extension: 2023.4.11
- Browser: Chrome
    (technically Brave -- fork of Chrome, compatible with Chrome apps -- but also checked on Chrome itself and same behavior)

- Extension: 20xx-xx-xx
- Browser: 
- OS: 

## Additional Information

(I seem to recall this is new behavior, so maybe it's a version thing?  I'm not 100% sure I'm remembering that right though)

![image](https://user-images.githubusercontent.com/374026/232556879-85c0fc56-5781-4562-9977-80b117fbba05.png)

**Comment by dharb** [comment]
Hi @JonLoesch, thanks for the detailed report! I've repro'd the issue and will get a fix out asap. What's happening here is we recently implemented a heuristic that hides empty ad placeholders on pages, and the HTML structure of the header on this website is an edge case that our heuristic is considering to be empty. Appreciate you raising the issue here.
