### ISSUE TITLE
Feature request: DNS privacy

### ISSUE THREAD

**Issue by svenssonaxel** [duckduckgo/duckduckgo-privacy-extension#200]
DNS is leaking information about what sites are visited, and it isn't protected by HTTPS-everywhere.

It would be nice to have the plugin force the browser to use one of the encrypted DNS-successor protocols (DNS over TLS or DNS over HTTPS). If the DNS server indicated by the operating system doesn't support any of the encrypted protocols, the plugin could either fallback to standard DNS with the same server, or use a public, privacy respecting, encrypted DNS service. Cloudflare, Google and Quad9 are possible candidates for this.

**Comment by tscpd** [comment]
It is already included. In Firefox network.trr.mode set to 2 should do it for Android, right? There already is the privacy dns named https://mozilla.cloudflare-dns.com/dns-query

**Comment by jonathanKingston** [comment]
Unfortunately extensions can't set DNS however this is on our radar for other clients.

As mentioned in Firefox you can set DoH to be enabled depending on your region otherwise/additionally you can set it at the OS level to a DNS provider you trust with your requests.

I'm going to close this out as we're investigating it further but don't immediately have anything to add here.
