### ISSUE TITLE
When I open a non https site the function globalThis.crypto.randomUUID() is called, but that does not exists

### ISSUE THREAD

**Issue by air2** [duckduckgo/duckduckgo-privacy-extension#2307]
## Description
The http://mypc:4400/somesite/duckduckgo-privacy-protection.js?scope=injectfirefox script has a call to `globalThis.crypto.randomUUID()` however because the site (in this case some local site), is accessed over http, this function is not supported.

## Steps to Reproduce

1. open the console in firefox
2. visit http://httpforever.com/

**Expected behavior:**
No errors

**Actual behavior:**

TypeError: globalThis.crypto.randomUUID is not a function inject.js:2648:54

**Versions**

- Extension: 2023.10.12
- Browser:  Firefox 119.0 (x64)
- OS: Windows 11

## Additional Information
1. Is the issue repeatable or intermittent? repeatable 
2. Did this issue start after an upgrade to a new extension version? I do not know, I just noticed the error a couple of days ago.
3. Are there any errors in the extension debugging console? Yes, that is the thingy
4. Include screenshots if they're helpful.

**Comment by air2** [comment]
Owh to be clear, this function should not be called on http sites, it is not supported on http sites

**Comment by sammacbeth** [comment]
Thanks for reporting. It looks like the code here was trying to be defensive for the case when `crypto.randomUUID` is missing, but was just testing if `globalThis.crypto` was falsy (which it is not in insecure contexts). This was fixed in https://github.com/duckduckgo/content-scope-scripts/commit/5246940ce79fc99d66b69cd11f4297f442478309 and this fix is already in the released version of the extension.
