### ISSUE TITLE
CTA popups from Hubspot are being blocked

### ISSUE THREAD

**Issue by klu2** [duckduckgo/duckduckgo-privacy-extension#2419]
## Description

The DuckDuckGo Privacy extension blocks CTA popups from Hubspot. 

## Steps to Reproduce

We are using a new popup mechanism from Hubspot for Call-To-Action fields (CTA) and embedded that on our homepage on https://www.greenyplus.com. If you scroll down, you find a green button with the label "Zum Newsletter anmelden" (english: register to newsletter).

**Expected behavior:**

If you open the page without the DuckDuckGo extension (both in Firefox and in Chrome), a popup opens where you can fill out a form.

**Actual behavior:**

When the extension is active, the popup is being blocked.

Looking at the console, you see a couple of scripts from Hubspot being blocked:, and i believe the crucial one is https://js-eu1.hubspot.com/web-interactives-embed.js

**Versions**

- Extension: 2023.12.6
- Browser: Firefox, Chrome
- OS: Windows

## Additional Information

This ticket is similar to #554, but that has been closed already 2,5 years ago, so I decided to create a new one.

**Comment by sammacbeth** [comment]
Thanks for the report here, and sorry for the slow turnaround - we've now mitigated this by making an exception for this blocking rule. This should be picked up immediately by all extension users: https://github.com/duckduckgo/privacy-configuration/pull/1799

**Comment by jdinbound** [comment]
Hello, first time commenting on a repo like this, I hope this is the right spot. 

We have the HubSpot scheduler embedded into our website. With the DuckDuckGo Privacy Essentials plugin installed, it blocks this embedded form on Chrome. Searching for the issue led me here. Perhaps there is another exception that needs to be added, OR, I have embedded the scheduler improperly. 

View the issue here: 

https://sittadel.com/start/

I'll check this thread in a week to see if it is active, and if not I will perhaps open another or a support ticket. Thanks!
