### ISSUE TITLE
GPC exclusion list doesn't have a formally documented update and maintenance process

### ISSUE THREAD

**Issue by eligrey** [duckduckgo/duckduckgo-privacy-extension#2765]
GPC exclusion list entries should include information as to why the exclusions were added, and these entries should be reviewed on a recurring basis to see if they are still needed.

Additionally, Verizon would like to be removed from this list. Whatever they were using in the past that caused issues with GPC is probably not present anymore, and this exclusion functionality has prevented Transcend Consent Management (used on Verizon sites) from receiving GPC signals for this extension's users.

**Comment by dharb** [comment]
Hi @eligrey, we do include information for all privacy protection exclusions that we ship to resolve site breakage, GPC included. You can find this info in https://github.com/duckduckgo/privacy-configuration.

We also do review GPC exclusions on a regular basis and remove them when the underlying issue has been resolved. Whenever we reproduce a reported site breakage caused by the GPC signal, the first thing we do is contact the site owner to inform them of the issue and ask for resolution. If we receive a response and the site owner confirms that they have fixed the issue, we remove the exclusion immediately. Otherwise we check back every few months to see if the issue has been resolved, and if so we remove the exclusion.

In Verizon's case, we added a GPC exclusion because they weren't loading reCAPTCHAs in a few places on their website when the GPC signal was present, which was preventing users from submitting forms. This exclusion was removed earlier this week during a routine review after we confirmed the reCAPTCHA issue had been resolved, so you should be seeing GPC signals from our users on verizon.com now.

**Comment by eligrey** [comment]
Thanks for the update. I'll let Verizon know that this is fixed and should be reaching DDG PE users shortly
