### ISSUE TITLE
Extension violates Content-Security-Policy

### ISSUE THREAD

**Issue by jribbens** [duckduckgo/duckduckgo-privacy-extension#367]
## Description

When the extension blocks things such as Google Analytics, if the site in question has a Content-Security-Policy then the code that the extension inserts violates the policy, causing false reports of policy violations.

## Steps to Reproduce

Using Chrome, go to the example page I have made at https://unequivocal.eu/duckduckgo-issue.html (or presumably any page which uses Google Analytics and has a Content-Security-Policy with a report-uri).
 
**Expected behavior:**

The analytics would be blocked without generating policy violations.

**Actual behavior:**

Observe in the network tab that Chrome generates a false report. From the console it can be seen that this is because the extension is trying to insert a script with `src=data:...`. Obviously as well as the false report, whatever it is that that script is supposed to be doing will not happen.

**Versions**

- Extension: 2019.3.6
- Browser: Chrome 73
- OS:  Windows 10

**Comment by jdorweiler** [comment]
@jribbens, thanks. I'm going to make an internal task to look into it.

**Comment by acsant** [comment]
@jdorweiler Here's my thought process behind this:
- Since the violation showed up, it has to be something in the background script - according to google CSP doesn't have power over content scripts on injection for chrome extensions
- Looking into background script, there's a list of surrogates that are loaded in base64 encoded to provide the least minimal functionality for all the blocked scripts
- Here's a list of those: https://duckduckgo.com/contentblocking.js?l=surrogates
- The example site linked in the issue loads `google-analytics.com/ga.js`, which is the first one in the surrogate's list. 
- If you open the src for the blocked request from the networks tab on that example page, you will see that it is indeed that surrogate which is causing that CSP violation
As a result, it's just that the surrogate isn't loaded but the actual blocking should work as expected. The solution would be to add `data:` to the CSP policy I believe. Content scripts in chrome extensions have alot of power. You could just have your content script whitelist `data:` in CSP policies if there exists one - not sure how "legal" this is though.

**Comment by jdorweiler** [comment]
uBlock has an interesting solution to this. They're keeping the surrogates in `web_accessible_resources` and generating an access token when the extension starts up. https://github.com/gorhill/uBlock/issues/2823

**Comment by akanshgulati** [comment]
@acsant  are you working on it?

**Comment by jonathanKingston** [comment]
This was resolved with a recent update of the extension so there are no longer CSP issues from this feature. We do still trigger some CSP issues in Firefox however this is to be resolved soon also.

**Comment by zflat** [comment]
I encountered this error in Firefox: "Content Security Policy: The page’s settings blocked the loading of a resource at inline (“style-src”)." Leading to the call `document.head.appendChild(styleTag);` in this code:

```
/**
   * Create styletag for strict hide rules and append it to document head
   * @param {Object[]} rules
   * @param {string} rules[].selector
   * @param {string} rules[].type
   */
  function injectStyleTag (rules) {
      const styleTag = document.createElement('style');
      let styleTagContents = '';

      rules.forEach((rule, i) => {
          if (i !== rules.length - 1) {
              styleTagContents = styleTagContents.concat(rule.selector, ',');
          } else {
              styleTagContents = styleTagContents.concat(rule.selector);
          }
      });

      styleTagContents = styleTagContents.concat('{display:none!important;min-height:0!important;height:0!important;}');
      styleTag.innerText = styleTagContents;

      document.head.appendChild(styleTag);
  }
```

The CSP header is:
> content-security-policy:  script-src 'self' https: http:; object-src 'none'; base-uri 'none'; style-src 'self' ; font-src 'self' ;

Can this extension function without appending style to the document.

**Comment by wintheriscomming** [comment]
I also have this problem:
![image](https://user-images.githubusercontent.com/26056995/225624359-a4150eb9-bdac-4681-9dcb-c9172ec0ef5b.png)

```
dev-server.js?2743:59 Refused to load the stylesheet 'data:text/css,%5Bid*%3D'google_ads_iframe'%5D%2C%5Bid*%3D'taboola-'%5D%2C.taboolaHeight%2C.taboola-placeholder%2C%23credential_picker_container%2C%23credential_picker_iframe%2C.google-one-tap-modal-div%7Bdisplay%3Anone!important%3Bmin-height%3A0!important%3Bheight%3A0!important%3B%7D' because it violates the following Content Security Policy directive: "default-src 'self' 'unsafe-inline' 'unsafe-eval'". Note that 'style-src-elem' was not explicitly set, so 'default-src' is used as a fallback.

injectStyleTag @ dev-server.js?2743:59
extractTimeoutRules @ dev-server.js?2743:59
applyRules @ dev-server.js?2743:59
(anonymous) @ dev-server.js?2743:59
13:52:41.375 
```

**Comment by jonathanKingston** [comment]
@zflat and @wintheriscomming this has been disabled so it shouldn't happen any more.

I'm going to close this out as we've had a few CSP issues in the past and they're not all related.

/cc @dharb @jdorweiler @kzar and @sammacbeth
