### ISSUE TITLE
Listing for Microsoft Edge (chromium version)

### ISSUE THREAD

**Issue by superusercode** [duckduckgo/duckduckgo-privacy-extension#433]
## Summary
There is no work to port the extensions since the new edge is based on chrome. All users on Windows/macOS (and Linux in the near future) are already able to install it from the chrome web store when prompted to enable downloads from the CWS. The extension submission process is detailed at https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/publish-extension

## Motivation
Makes it easier for Microsoft Edge chromium users to get the extension and easier to deploy. Microsoft Edge chromium will replace the existing edge via a windows update later this year when the new windows feature update releases.

**Comment by superusercode** [comment]
this would supersede #117 since the EdgeHTML version is no longer supported.

**Comment by jonathanKingston** [comment]
So we already publish to the Edge store (https://microsoftedge.microsoft.com/addons/detail/duckduckgo-privacy-essent/caoacbimdbbljakfhgikoodekdnlcgpk) but due to Edge removing the extension heavily we don't really promote it due to poor user experience.

Anyway closing out as there's nothing to do here as I understand it.
