### ISSUE TITLE
Fallback behavior for referrer truncation results in an invalid value

### ISSUE THREAD

**Issue by palant** [duckduckgo/duckduckgo-privacy-extension#530]
The fallback behavior for referrer truncation in the `fingerprint-protection.js` content script looks as follows:

https://github.com/duckduckgo/duckduckgo-privacy-extension/blob/e15a3fba9fc46bca8f38114c574207e68b0446d6/shared/data/fingerprint-protection.js#L111-L114

This sets the referrer to hostname only which isn’t a valid URL. I guess that the idea here was to use `new URL(document.referrer).origin` instead which makes more sense.

**Comment by Charlie-belmer** [comment]
Thanks for this report as well @palant! Nice find, I'll include a fix for this with the other fingerprint items as well.

**Comment by kberridge** [comment]
I discovered your browser extension is stripping the port off the HTTP Referer request header (should be http://localhost:65314 but is http://localhost). Which breaks APIs that expect the Referer to match! In chrome, edge, and firefox. Disabling duck duck go extension fixes it.

Looks like this issue could be the same thing?  I didn't want to open a duplicate if so.

**Comment by Charlie-belmer** [comment]
Thanks for mentioning this @kberridge. It's a slightly different issue, but I'll take a look!

**Comment by sammacbeth** [comment]
This looks likely - the `hostname` attribute of a `URL` strips the port (while `host` includes it). It looks like the `origin` fix described here will also work with ports:
```javascript
const url = new URL('http://localhost:1234')
url.hostname // == "localhost"
url.host // == "localhost:1234"
url.origin // == "http://localhost:1234"
```

**Comment by weaversam8** [comment]
Is it normal for the DDG privacy extension to trim subdomains too? The `Referer` header for an iframe was being set to `site.com` when I was making a request from `subdomain.site.com`, which was breaking permitted embeddable domains on said iframe.

**Comment by sammacbeth** [comment]
> Is it normal for the DDG privacy extension to trim subdomains too? The `Referer` header for an iframe was being set to `site.com` when I was making a request from `subdomain.site.com`, which was breaking permitted embeddable domains on said iframe.

Yes. If a request is made to a third-party tracker domain the referer will be truncated to eTLD+1.

**Comment by weaversam8** [comment]
What would be the expected flow to override this in this example? If an embedded domain is whitelisted to only be embedded on a subdomain, it won't load in this case. For context, [Cloudflare Stream](https://developers.cloudflare.com/stream/) is the service that broke in this example, with their [allowed origin domains](https://developers.cloudflare.com/stream/viewing-videos/securing-your-stream#security-considerations) security feature blocking access since the subdomain was permitted but only the root domain was passed in the referrer.

Can't this protection be routed around by malicious actors by constructing an iframe using Javascript that embeds the true origin as a query string parameter?
