### ISSUE TITLE
unable to log in to PNC banking on Firefox

### ISSUE THREAD

**Issue by ranimal19** [duckduckgo/duckduckgo-privacy-extension#616]
## Description
 cannot log in to www.pnc.com; will get an error message. Turning of the extension fixes the issue.

## Steps to Reproduce

1. step 1 use your username and password to log in to www.pnc.com
2. step 2 behold the error message.
3. ...

**Expected behavior:**
 should be able to log in to my account

**Actual behavior:**
 error message

**Versions**

- Extension: 20xx-xx-xx
- Browser: 
- OS:

**Comment by kevinrtai** [comment]
This happens on multiple websites, including chipotle.com and walgreens.com. The issue seems to be related to CORS. When I attempt to log in with the extension, I get the error `CORS Missing Allow Origin`

![image](https://user-images.githubusercontent.com/8663153/115415433-e73b0980-a1c4-11eb-911a-87d023c80e8e.png)

**Versions:**
OS: Ubuntu 20.04.2 LTS
Browser: Firefox 87.0

**Comment by sammacbeth** [comment]
Thanks for the reports. We have heard that PNC are now only supporting Chrome and Edge browsers, and blocking logins from other browsers. @ranimal19 which browser are you using?

@kevinrtai Thanks for reporting those issues. I was able to reproduce the chipotle issue, and we'll fix that ASAP. Could you perhaps describe the issue you're having with walgreens.com so we can look into that one too?

**Comment by ranimal19** [comment]
@sammacbeth I am using firefox. I can login to PNC when I turn the DuckDuck extension off.

**Comment by jonathanKingston** [comment]
@ranimal19 are you able to check again if our list update fixed the issue?

If not we can disable all protections for a short while on this site, whilst we debug further.
